# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_compute_single_rcpp <- function(y, start_beta, ytx, XtX_reduce, lambda, alpha, xtx, i_iter) {
    .Call(`_PO_EN_sum_compute_single_rcpp`, y, start_beta, ytx, XtX_reduce, lambda, alpha, xtx, i_iter)
}

rcpp_hello_world <- function() {
    .Call(`_PO_EN_rcpp_hello_world`)
}

